name: Build/Unit Tests
permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  spring:
    name: App Build and Test
    runs-on: ubuntu-latest
    env:
      ACTION_DEBUG: true

    steps:   
      
      # Setup Java Environment
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
          cache: maven

      - name: Checkout Repository
        uses: actions/checkout@v6

     # Run Maven Verify      
      - name: Build with Maven
        run: mvn -B install -P all --file src/pom.xml

    #Removed code climate
